apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: prod
spec:
  selector:
    app: apigateway
  ports:
  - port: 5000
    targetPort: 5000
    name: apigateway
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      nodeName: app-node-1
      containers:
        - name: apigateway
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          env:
            - name: KAFKA_HOST
              value: kafka.kafka
            - name: KAFKA_PORT
              value: "9094"
            - name: KAFKA_PREFIX
              value: prod
          envFrom:
            - secretRef:
                name: apigateway-secrets
                optional: false
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apigateway-ingress
  namespace: prod
spec:
  rules:
    - host: prod.api.116.203.242.235.xip.io
      http:
        paths:
          - backend:
              serviceName: apigateway
              servicePort: 5000
  tls:
    - hosts:
        - 116.203.242.235.xip.io
